---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: gobadiah/macos-sierra
    driver:
      vagrantfiles:
        - .vagrant.rb

suites:
  - name: default
    run_list:
      - recipe[workstation]
    attributes:
